var homePage = require('./home');
const BasePage = require('./base');


homePage.accessLandingPage();
var accessRegistrationPage = homePage.accessRegistrationPage();
var register = accessRegistrationPage.registerUser();
var homePage = register.logOut();
homePage.accessLandingPage();
//homePage.tearDown();
homePage.accessRegistrationPage();
accessRegistrationPage.registerUser();
register.logOut();
homePage.accessLandingPage();
//homePage.tearDown();
homePage.accessRegistrationPage();
accessRegistrationPage.registerUser();
register.logOut();
homePage.accessLandingPage();
//homePage.tearDown();
homePage.accessRegistrationPage();
accessRegistrationPage.registerUser();
register.logOut();
homePage.accessLandingPage();
//homePage.tearDown();
homePage.accessRegistrationPage();
accessRegistrationPage.registerUser();
register.logOut();
homePage.accessLandingPage();
//homePage.tearDown();
homePage.accessRegistrationPage();
accessRegistrationPage.registerUser();
register.logOut();
homePage.accessLandingPage();
//homePage.tearDown();
homePage.accessRegistrationPage();
accessRegistrationPage.registerUser();
register.logOut();
homePage.accessLandingPage();
//homePage.tearDown();
homePage.accessRegistrationPage();
accessRegistrationPage.registerUser();
register.logOut();
homePage.accessLandingPage();
//homePage.tearDown();
homePage.accessRegistrationPage();
accessRegistrationPage.registerUser();
register.logOut();
homePage.accessLandingPage();
//homePage.tearDown();
homePage.accessRegistrationPage();
accessRegistrationPage.registerUser();
register.logOut();
homePage.accessLandingPage();
//homePage.tearDown();
homePage.accessRegistrationPage();
accessRegistrationPage.registerUser();
register.logOut();
homePage.accessLandingPage();
//homePage.tearDown();
homePage.accessRegistrationPage();
accessRegistrationPage.registerUser();
register.logOut();
homePage.accessLandingPage();
//homePage.tearDown();
homePage.accessRegistrationPage();
accessRegistrationPage.registerUser();
register.logOut();
homePage.accessLandingPage();
homePage.tearDown();
